[global.tls]
certs = "/etc/letsencrypt/live/notinept.me-0001/fullchain.pem"
key = "/etc/letsencrypt/live/notinept.me-0001/privkey.pem"

[development]
address = "localhost"
port = 16161
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 16162
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 16161
log = "critical"
limits = { forms = 32768 }
